image: "fedora:32"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - bundle

before_script:
- dnf -y install glibc-static.i686 openssl-devel.i686 libstdc++-static.i686 glibc-devel.i686 cmake make gcc g++
- curl -o boost.tar.gz -L https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.tar.gz
- tar -xf boost.tar.gz
- cd boost_1_75_0 && ./bootstrap.sh && ./b2 variant=release link=static address-model=32

build:
  stage: build
  script:
    - cmake -B build/ -D "CMAKE_BUILD_TYPE=Release" -D "BOOST_LIBRARYDIR=boost_1_75_0/stage/x86/Release/lib" -D "BOOST_ROOT=boost_1_75_0"
    - cmake --build build/ --config Release
  artifacts:
    paths:
      - build/websocket.ext.so
  